fix: Updating relationships through /trackedentityinstances endpoint shows error 500 [ DHIS2-13919 ]
dhis2/dhis2-core pull request #12129
Opened 2022-10-14 17:04 UTC by lucaCambi77

In relationship update during teis import, we were persisting an object with missing references to the DB object making it invalid.
In this PR we fix only using the DB object updating what is in the payload without creating any transient object.

2022-10-17 07:16 UTC, stian-sandvold requested changes
Looks good, remember to add tests as well! :)

2022-10-17 07:16 UTC, stian-sandvold commented on dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
> +        RelationshipItem fromItem = relationshipDb.getFrom();
Setting the from and to could probably be done in a separate method to reduce the code duplication :)

2022-10-18 04:10 UTC, stian-sandvold approved these changes

2022-10-18 06:56 UTC, enricocolasante approved these changes

2022-10-19 07:37 UTC, merged