[WIP] feat: Create new endpoint/entity for ExpressionDimensionItem [2.40-DHIS2-13988]
dhis2/dhis2-core pull request #12231
Opened 2022-11-01 08:04 UTC by d-bernat

please see: https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/boards/104?modal=detail&selectedIssue=DHIS2-13988&quickFilter=497

2022-11-01 13:37 UTC, gnespolino approved these changes

2022-11-01 13:37 UTC, gnespolino commented on dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ExpressionDimensionItemController.java
> + */
please remove this empty comment

2022-11-01 13:37 UTC, gnespolino commented on dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ExpressionDimensionItemController.java
> + */
please remove this empty comment

2022-11-01 13:37 UTC, gnespolino commented on dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ExpressionDimensionItemController.java
> +            expressionService.addExpressionDimensionItem( expressionDimensionItem );
is it safe to add an expressionItem without checking if another with the same id already exists?

2022-11-01 13:37 UTC, gnespolino commented on dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ExpressionDimensionItemController.java
> +            expressionService.updateExpressionDimensionItem( expressionDimensionItem );
is it safe to update an expressionDimensionItem if the id doesn't exist?

2022-11-01 14:26 UTC, maikelarabori requested changes
Left some comments that will probably require changes @d-bernat.

Thanks!

2022-11-01 14:26 UTC, maikelarabori commented on dhis-2/dhis-api/src/main/java/org/hisp/dhis/expressiondimensionitem/ExpressionDimensionItem.java
> +public class ExpressionDimensionItem
I think we should extend `BaseIdentifiableObject`, so you get all required default/standard attributes for free.
These attributes should be added as columns to your table, respecting the same column types and max chars from existing tables.
You should get for free equals/hashcode, translation, etc.

2022-11-16 10:26 UTC, gnespolino commented on dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
> -        return dataDimensionItems.stream().map( DataDimensionItem::getDimensionalItemObject )
it was enough to add `.filter(Objects::nonNull)` in the stream chain.

2022-11-16 13:18 UTC, maikelarabori requested changes
Hey @d-bernat, looks good in general :+1: 
I left a few comments that would be nice to be reviewed before merging it.

Thanks!

2022-11-16 15:48 UTC, maikelarabori approved these changes

2022-11-16 15:52 UTC, merged