fix: Fetch nested event notes in trackedEntityInstance endpoint [DHIS2-11731]
dhis2/dhis2-core pull request #12431
Opened 2022-11-29 12:13 UTC by zubaira

2022-11-30 07:42 UTC, enricocolasante requested changes
A bug fix like this should have a test to clearly show what was fixed and what is the current behaviour

2022-11-30 12:32 UTC, zubaira commented
> A bug fix like this should have a test to clearly show what was fixed and what is the current behaviour

resolved

2022-12-01 07:55 UTC, enricocolasante approved these changes

2022-12-07 10:52 UTC, stian-sandvold approved these changes

2022-12-07 10:52 UTC, merged