Additional metadata checks for organisation units
dhis2/dhis2-core pull request #12478
Opened 2022-12-05 10:45 UTC by jason-p-pickering

2022-12-07 11:07 UTC, olavpo approved these changes

2022-12-08 15:37 UTC, jbee requested changes
Overall it looks good. A couple of cleanup/code-style/convention things:

* method names should not start with an upper case letter
* don't use `null` for any collection value, use empty ones and check `!isEmpty()` instead of `!= null`, e.g. `Set.of()`
* fields in test classes should be `private`

2022-12-08 15:37 UTC, jbee commented on dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/AbstractDataIntegrityIntegrationTest.java
> +    public final void DataIntegrityDivideByZeroTestTemplate( String detailsIssueType, String check )
It is not clear from the name what this does. 
Maybe a name like `assertNoIssues`.

2022-12-08 15:37 UTC, jbee commented on dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/dataintegrity/AbstractDataIntegrityIntegrationTest.java
> +    public final void DataIntegrityNegativeTestTemplate( String detailsIssueType, String check )
This looks almost the same as the one above just that it expects a percent 0 instead percent null. 
You can make them one method with an argument for the expected percent:
```java
void assertNoIssues( tring detailsIssueType, String check, boolean percentageIsPresent )
```

2022-12-09 11:32 UTC, olavpo approved these changes

2022-12-09 14:06 UTC, jbee approved these changes

2022-12-09 14:15 UTC, merged