feat: add Metadata package import changelog [DHIS2-14460]
dhis2/dhis2-core pull request #13210
Opened 2023-03-02 18:31 UTC by vietnguyen

https://dhis2.atlassian.net/browse/DHIS2-14460

2023-03-03 07:58 UTC, netroms approved these changes

2023-03-03 09:23 UTC, larshelge requested changes
Looks good. Let's discuss the data model a bit.

2023-03-07 10:12 UTC, larshelge commented on dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.40/V2_40_20__Add_table_metadata_package.sql
> +
Remove blank lines.

2023-03-27 07:17 UTC, vietnguyen commented
Need to finalize the specification for this feature. Close the PR for now.

2023-03-27 07:17 UTC, closed without merging