fix: Set minimum Java version to 17 [DHIS2-14889]
dhis2/dhis2-core pull request #13393
Opened 2023-03-21 13:51 UTC by larshelge

Updates the DHIS 2 backend to require/support JDK 17.

2023-03-22 08:10 UTC, netroms approved these changes

2023-03-22 12:18 UTC, Philip-Larsen-Donnelly commented
Can we put this in draft until it is supported by our build and deployment environments?

2023-03-23 14:29 UTC, radnov requested changes

2023-04-03 09:13 UTC, jbee approved these changes

2023-04-17 20:14 UTC, merged