chore: Use only new tracker fields name in JdbcEventStore [TECH-1526]
dhis2/dhis2-core pull request #13504
Opened 2023-03-31 11:43 UTC by enricocolasante

2023-04-03 08:58 UTC, teleivo requested changes
Yeah 😄 we are getting closer 🥳  

I think `EventSearchParams.EVENT_CREATED_BY_ID` has a casing issue (which is why I hit the request changes).

Apart from that just some minor things we can do in this PR or another one. I went through https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-master/new-tracker.html#changes-in-the-api
and it looks good to me

2023-04-03 08:58 UTC, teleivo commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/event/DefaultEventService.java
>          if ( violation == null && params.hasLastUpdatedDuration()
```suggestion
        if ( violation == null && params.hasUpdatedAtDuration()
```

2023-04-03 08:58 UTC, teleivo commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/event/EventSearchParams.java
> +    public static final String EVENT_CREATED_BY_ID = "createdby";
```suggestion
    public static final String EVENT_CREATED_BY_ID = "createdBy";
```

2023-04-03 08:58 UTC, teleivo commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/event/EventSearchParams.java
>      public boolean hasLastUpdatedStartDate()
```suggestion
    public boolean hasUpdatedAtStartDate()
```

2023-04-03 08:58 UTC, teleivo commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/event/EventSearchParams.java
>      public boolean hasLastUpdatedEndDate()
```suggestion
    public boolean hasUpdatedAtEndDate()
```

2023-04-03 08:58 UTC, teleivo commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/event/EventSearchParams.java
>      public boolean hasLastUpdatedDuration()
```suggestion
    public boolean hasUpdatedAtDuration()
```

2023-04-03 08:58 UTC, teleivo commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/event/EventSearchParams.java
> +        return scheduleAtStart;
Should we make this consistent with the `updatedAt` ones which are all `updatedAtStartDate/EndDate`?

So either `scheduleAtStartDate` or remove the `Date` suffix from the other fields/setters/getters

2023-04-03 08:58 UTC, teleivo commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/event/JdbcEventStore.java
>          builder.put( "trackedEntityInstance", "tei_uid" );
is now `trackedEntity`

2023-04-03 08:58 UTC, teleivo commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/event/EventSearchParams.java
> +    public static final String EVENT_LAST_UPDATED_ID = "updatedBy";
```suggestion
    public static final String EVENT_UPDATED_BY_ID = "updatedBy";
```

2023-04-03 08:58 UTC, teleivo commented on dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/TrackerExportTests.java
> +    void shouldReturnInvalidPropertyWhenOrderOnLegacyCreatedField()
Can you please add

`// TODO(tracker): remove with old tracker`

so we remember to remove it one day 😅

2023-04-03 11:33 UTC, teleivo approved these changes

2023-04-04 06:02 UTC, muilpp approved these changes

2023-04-04 06:02 UTC, merged