chore: rephrase order validation message TECH-1535
dhis2/dhis2-core pull request #14876
Opened 2023-08-10 07:25 UTC by teleivo

to work for one or more fields that cannot be ordered by.

2023-08-10 12:55 UTC, muilpp approved these changes

2023-08-11 12:19 UTC, zubaira approved these changes

2023-08-11 12:20 UTC, zubaira requested changes
there are some conflicts in the PR

2023-08-12 12:23 UTC, vietnguyen approved these changes

2023-08-13 07:50 UTC, stian-sandvold approved these changes

2023-08-13 07:52 UTC, merged