fix: solve issues around OpenAPI query param definitions which are ca…
dhis2/dhis2-core pull request #14888
Opened 2023-08-11 10:58 UTC by claudemamo

…using code generation to choke

2023-08-15 15:03 UTC, jbee commented on dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/Property.java
> +@Getter
`@Value` does imply `@Getter` I think

2023-08-15 15:12 UTC, jbee requested changes

2023-08-15 15:12 UTC, jbee commented on dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/Property.java
> +        && Stream.of("set")
This seems unnecessarily complicated. 
Just `name.startsWith("set") && name.length() > 3 && isUpperCase(name.charAt(3))`  seems more clear.

2023-08-15 15:12 UTC, jbee commented on dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/openapi/Property.java
> +        getType(m, isSetter(m) ? m.getParameterTypes()[0] : m.getGenericReturnType()),
I think this should be `m.getGenericParameterTypes()[0]`

2023-08-15 15:12 UTC, jbee commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/TrackerIdSchemeParam.java
> +// FIXME: omitting this will result in a complex type for the query param in the OpenAPI definition
I think we should leave this as `TODO` not `FIXME`.

2023-08-15 15:56 UTC, jbee approved these changes

2023-08-16 08:30 UTC, david-mackessy approved these changes

2023-08-16 08:31 UTC, netroms approved these changes

2023-08-16 08:45 UTC, merged