fix: /tracker/events?order=<attributeUID> filters out events without attribute [ DHIS2-15679 ]
dhis2/dhis2-core pull request #15465
Opened 2023-10-23 12:04 UTC by lucaCambi77

[DHIS2-15679](https://dhis2.atlassian.net/browse/DHIS2-15679)
Apply the same logic as in the HibernateTrackedEntityStore to not exclude (use a LEFT JOIN) in the result set the attributes we want to order but are not filterable. Use an INNER JOIN otherwise

2023-10-24 07:24 UTC, muilpp approved these changes

2023-10-24 08:32 UTC, enricocolasante requested changes
It seems to me that the case `/tracker/events?attribute=<attributeUid>` is not working properly anymore

2023-10-24 13:44 UTC, lucaCambi77 commented
@enricocolasante can you make an example of the failing expectations for that? I don't see any `/events?attribute` parameter option but maybe I am missing something

2023-10-24 13:52 UTC, enricocolasante requested changes

2023-10-24 13:52 UTC, enricocolasante commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/event/EventQueryParams.java
> +        .filter(a -> !a.getValue().isEmpty())
If we filter by an attribute and we do not add any filter on the value this should still translate to a `INNER JOIN`.
Do we have a test like `shouldFilterEventsByAttributeWithNoValuesAndFilterOutEventsWithATrackedEntityWithoutThatAttribute`

2023-10-27 10:57 UTC, enricocolasante approved these changes
Just remove the page info in TrackedEntityQueryParams

2023-10-27 10:57 UTC, enricocolasante commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/export/trackedentity/TrackedEntityQueryParams.java
> +  public static final int DEFAULT_PAGE = 1;
All this page info must be removed.
It was removed in a previous PR, probably got lost in the merge

2023-10-27 12:43 UTC, merged