fix: Migrate event status VISITED to ACTIVE
dhis2/dhis2-core pull request #15576
Opened 2023-11-02 14:20 UTC by abyot

2023-11-11 09:42 UTC, enricocolasante requested changes
We should have at least a test verifying the change of the PR.

`VISITED` status is present in a lot of different places in the system, it would be good to have a more organic solution for this migration.
In my head `VISITED` should be a status that makes sense only for the client, then in our service layer and DB layer, we shouldn't even know that such status exists.
Any if that check if the status is `VISITED` is a potential source of errors and this checks should be grouped just in one layer of the system

2023-11-13 07:59 UTC, abyot commented
> We should have at least a test verifying the change of the PR.
> 
> `VISITED` status is present in a lot of different places in the system, it would be good to have a more organic solution for this migration. In my head `VISITED` should be a status that makes sense only for the client, then in our service layer and DB layer, we shouldn't even know that such status exists. Any if that check if the status is `VISITED` is a potential source of errors and this checks should be grouped just in one layer of the system

This is a minor issue with a deprecated API. Otherwise, we have a preprocessor and associated test that converts all incoming `VISITED` status to `ACTIVE` in the new tracker API.

2023-11-27 08:03 UTC, enricocolasante approved these changes

2023-12-04 07:44 UTC, zubaira approved these changes

2023-12-05 08:16 UTC, merged