chore: Remove getEnrollments(Program) [DHIS2-17712]
dhis2/dhis2-core pull request #18188
Opened 2024-07-24 11:26 UTC by muilpp

2024-07-24 12:08 UTC, enricocolasante commented on dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/EnrollmentServiceTest.java
> +    List<Enrollment> enrollments = eventProgramEnrollmentService.getEnrollments(programA);
As the previous PR, I think it make sense to create `EventProgramEnrollmentServiceTest` to test this method.
This test class should be removed when this Jira task is done, but we will need more time to solve the program/tracker event separation.

2024-07-25 07:28 UTC, enricocolasante approved these changes

2024-07-25 09:24 UTC, teleivo requested changes

2024-07-25 09:24 UTC, teleivo commented on dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultEventProgramEnrollmentService.java
> +  // TODO The CopyService is currently copying enrollments from tracker programs. We need to discuss
Please use `TODO(tracker)` or `TODO(issue nr)` as such todos are hard to find and todos without owners have even less chances of getting done 😁

2024-07-25 09:24 UTC, teleivo commented on dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/program/EventProgramEnrollmentServiceTest.java
> +    assertEquals(2, enrollments.size());
please use `assertContainsOnly` or `assertEquals(List.of(), enrollments)` if order matters

this style of assertions are a pain if they fail on CI which is why we should stop writing them this way 😬

2024-07-25 10:01 UTC, teleivo approved these changes

2024-07-25 10:01 UTC, merged