chore: Remove getEnrollments(Program,Status) [DHIS2-17712]
dhis2/dhis2-core pull request #18201
Opened 2024-07-25 11:39 UTC by muilpp

2024-07-25 13:03 UTC, enricocolasante requested changes

2024-07-25 13:03 UTC, enricocolasante commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/SimpleEventSMSListener.java
> +          new ArrayList<>(enrollmentService.getEnrollments(null, program, EnrollmentStatus.ACTIVE));
Is this call raise an NPE?

2024-07-25 13:03 UTC, enricocolasante commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/imports/sms/SingleEventListener.java
> +              enrollmentService.getEnrollments(
Here as well. NPE

2024-07-25 13:57 UTC, enricocolasante approved these changes

2024-07-26 06:01 UTC, teleivo approved these changes

2024-07-26 06:01 UTC, merged