fix: index html caching
dhis2/dhis2-core pull request #18458
Opened 2024-08-27 13:53 UTC by KaiVandivier

This should fix these two issues, which both seem to be caused by HTML files being cached and served by the browser:
* [DHIS2-17782](https://dhis2.atlassian.net/browse/DHIS2-17782)
* [DHIS2-17804](https://dhis2.atlassian.net/browse/DHIS2-17804)

It seems that in v42, responses for HTML files are missing the `Cache-Control: no-cache, no-store, max-age=0, must-revalidate` headers that previous versions added to responses -- these changes reintroduce them

The change can be tested by opening up apps and checking the response headers on HTML files -- they should include the `Cache-Control` headers above. _Other_ requests should not all have the same headers -- a few do, like `/api/me/dashboard` and `api/system/info`, but not all. NB: If opening up apps at a URL that hosted a previous v42 instance, you made need to get past previously cached versions of `index.html`, which can be done by reloading multiple times, hard reloading, or using the `Disable Cache` option in the Network panel of dev tools

Here are some examples of response headers after the changes:
![Screenshot 2024-08-27 at 2 16 10 PM](https://github.com/user-attachments/assets/49f76d58-a4ad-430f-a8c0-469cb66fb9b8)
![Screenshot 2024-08-27 at 2 15 54 PM](https://github.com/user-attachments/assets/ae2a85a7-38e3-47e0-9bf8-1241afd6bfe4)
![Screenshot 2024-08-27 at 2 15 35 PM](https://github.com/user-attachments/assets/3dd951bf-9564-4701-b4bf-b7e933a1133
![Screenshot 2024-08-27 at 2 24 24 PM](https://github.com/user-attachments/assets/592f0b5e-296c-4736-9ebf-50b45db216e1)
![Screenshot 2024-08-27 at 2 23 35 PM](https://github.com/user-attachments/assets/fb28efc6-14a0-4edc-9fa6-cc87a5026183)
![Screenshot 2024-08-27 at 2 23 28 PM](https://github.com/user-attachments/assets/4e2dad9d-3507-4104-838d-1211790cf5b7)
6)

2024-08-27 14:46 UTC, amcgee commented on dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/HttpNoCacheFilter.java
> + * @author Lars Helge Overland
```suggestion
 * @author Kai Vandivier
```

2024-10-02 08:46 UTC, amcgee reviewed
Looking good!  Few minor comments as discussed.

@netroms could you take a quick look at this to make sure we're doing the filtering in the right place?  Thanks!

2024-10-02 08:46 UTC, amcgee commented on dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/servlet/DhisWebApiWebAppInitializer.java
> +    */
```suggestion
    /* Intercept index.html, plugin.html, and other html requests to inject no-cache
      headers using ContextUtils.setNoStore(response).
    */
```

2024-10-02 08:46 UTC, amcgee commented on dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/filter/HttpNoCacheFilter.java
> +public class HttpNoCacheFilter extends OncePerRequestFilter {
Let's rename this to `HtmlFileNoCacheFilter` or something similar to make sure it reflects the behavior

2024-10-08 09:30 UTC, amcgee approved these changes
This change looks good to me!  Tested here https://dev.im.dhis2.org/pr-18458

2024-10-09 06:02 UTC, netroms approved these changes

2024-10-09 07:49 UTC, jbee requested changes
No can't do it like this. I know of HTML we do want to cache. So the headers need to be added to the specific endpoints, not always for all HTML responses.

2024-10-09 08:36 UTC, amcgee commented
> No can't do it like this. I know of HTML we do want to cache. So the headers need to be added to the specific endpoints, not always for all HTML responses.

@jbee which HTML are you thinking of?

We discussed making the regex more targeted, we can do that if there are html files elsewhere that should be cached.  It is generally always problematic to cache application root html files, and this was the previous behavior.  @netroms and I also discussed that we need to address static asset caching headers more holistically so this will be updated before 42.

2024-10-10 12:33 UTC, jbee commented
@amcgee I was thinking about the `/openapi/openapi.html` and others in the `/openapi` path. But you are also allowed to use `/api/dataElements/openapi.html` and so forth.

2024-10-17 07:46 UTC, jbee approved these changes

2024-10-17 11:33 UTC, KaiVandivier commented
Thanks @jbee!

Regarding the Maps app, I tried switching the order of operations in the filter as recommended:
```java
chain.doFilter(request, response);

if (m.find() && HttpMethod.GET.matches(request.getMethod())) {
  ContextUtils.setNoStore(response);
}
```

But still the headers don't seem to get applied to the Maps app 🤔 any other ideas? @amcgee 

(This screenshot is from before changing the order, but it still looks the same after -- included for illustration)
![new-regex-maps-not-working](https://github.com/user-attachments/assets/947446c9-be39-4174-b70f-19d2fc646392)

2024-10-21 07:24 UTC, jbee commented
@KaiVandivier in that case I would revert the change of order again. Send me a message on slack so we can talk about the request this does and I maybe can help debugging it.

2024-11-04 17:27 UTC, KaiVandivier commented
The Maps HTML seems to be working fine on the IM deployment; maybe there was something weird on my local instance 🤔 

So I think this is nearly done; just discussing one last thing with Austin

![Screenshot 2024-11-04 at 18 23 04](https://github.com/user-attachments/assets/6fe8a6e0-267b-46f0-9870-5fdec0a7b43c)

2024-11-06 12:39 UTC, amcgee approved these changes

2024-11-06 12:42 UTC, merged