feat: password validation regexp in settings
dhis2/dhis2-core pull request #19574
Opened 2024-12-30 18:53 UTC by netroms

2025-01-10 10:37 UTC, larshelge approved these changes

2025-01-15 09:35 UTC, jbee requested changes

2025-01-15 09:35 UTC, jbee commented on dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/SystemSettings.java
> +            "^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[\\W_])[A-Za-z\\d\\W_]{%d,%d}$",
That regex seems too specific. With this a upper case letter must always be before a lower case one, both before a digit and all of them before a non-word character. All of that must be followed by the min-max number of letters, gitis, and non-word characters. That seems illogical. Why use `.*` in several places allowing anything but then at the end be so specific? I would assume `\W` basically excludes what you then included again with `A-Za-z\\d` so effectively that will be very close or similar to `.`. 

I think what you wanted to say is something entirely different where it is min-max number of characters for which at least one is a lower letter, one an upper letter, one a digit, and one a special character.

2025-01-15 09:37 UTC, jbee commented on dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/SystemSettings.java
> +            "^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[\\W_])[A-Za-z\\d\\W_]{%d,%d}$",
For example: `+1aaaaAA00` does not match. That has 8 letters but as I explained you basically ask for 4+min-max. But considering that, even `+1aaaaAA0012345676` would not match.

2025-01-15 09:43 UTC, jbee approved these changes

2025-01-20 13:44 UTC, merged