feat(apps to bundle): add cache cleaner app
dhis2/dhis2-core pull request #6106
Opened 2020-09-08 13:26 UTC by Mohammer5

The app has been re-written and is now supports feature toggling (although there are no features to toggle as there are no api requests).

This PR
- [x] adds the app to the `apps-to-bundle.json`
- [x] add a row to the README with the feature toggle apps

2020-09-08 14:07 UTC, amcgee approved these changes
LGTM

2020-09-15 08:58 UTC, stian-sandvold approved these changes

2020-10-20 12:42 UTC, varl requested changes
We don't need to add this again, the duplicate entries will fail.

2020-10-20 12:42 UTC, amcgee commented
Closing as this shouldn't be necessary, the README updates already happened.

2020-10-20 12:42 UTC, closed without merging