fix: [DHIS2-9428] Use report mode parameter to filter report data
dhis2/dhis2-core pull request #6122
Opened 2020-09-09 13:19 UTC by enricocolasante

2020-09-10 05:12 UTC, larshelge approved these changes

2020-09-15 08:48 UTC, stian-sandvold requested changes

2020-09-15 08:48 UTC, stian-sandvold commented on dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/utils/ImportUtils.java
> +    public static TrackerImportParams build(TrackerBundleParams params )
```suggestion
    public static TrackerImportParams build( TrackerBundleParams params )
```

2020-09-15 08:48 UTC, stian-sandvold approved these changes

2020-09-15 09:32 UTC, merged