fix: Add proxy initializer to fetch infrastructural data
dhis2/dhis2-core pull request #6152
Opened 2020-09-15 09:21 UTC by zubaira

2020-09-15 09:38 UTC, maikelarabori approved these changes

2020-09-15 09:54 UTC, luciano-fiandesio reviewed
hi @zubaira which collection was throwing a Lazy exception?

2020-09-15 10:26 UTC, zubaira commented on dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ConfigurationController.java
> +        IndicatorGroup group = configurationService.getConfiguration().getInfrastructuralIndicators();
@luciano-fiandesio IndicatorGroup class has a list of indicators.

2020-09-18 08:14 UTC, larshelge requested changes
This looks too arbitrary to me. It seems like we have a lot of Hibernate proxy initialization issues around now and we are adding fixes all over. Would be nice to find a more centralized solution. We should not expose Hibernate in the Web API controller layer.

2020-09-18 19:59 UTC, stian-sandvold approved these changes

2020-09-24 08:34 UTC, netroms commented
I have solved this problem without using Hibernate initialization, the core of the problem lies in the Hibernate5Module. I can't commit yet because @vietnguyen is working in parallel on fixing the issues with auditing that are also using the Hibernate5Module. So until then I think we should close this PR.

2020-09-25 03:58 UTC, closed without merging