fix: Reject duplicate events from current payload
dhis2/dhis2-core pull request #6267
Opened 2020-09-26 13:52 UTC by abyot

2020-09-28 08:10 UTC, luciano-fiandesio requested changes
Please see comments. In general, I think the logic that is used in the PR is very similar to what we already have in `ProgramInstanceRepeatableStageCheck`.
Additionally, I'm not sure I understand the concept of "duplicated" event: it seems to me that the duplication is based on `String eventContextId = programStage.getUid() + "-" + event.getEnrollment();`. Is that correct?

2020-09-28 11:19 UTC, abyot commented on dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
> +    private boolean isValidEvent(final WorkContext workContext, Event event, Set<String> importableStageEvents, final ImportSummaries importSummaries )
Ok, this is a good point. Will create this new class. But `EventManager` is checking existing or not events ?

2020-09-28 11:20 UTC, abyot commented on dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
> +            final ImportSummary is = new ImportSummary( ERROR, "ProgramStage " + event.getProgramStage() + " does not point to a valid programStage" )
hmmm... so what this check already plugged in? or does program stage check precede program check? I added it because of a test failure

2020-09-28 11:24 UTC, abyot commented on dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
> +                "ProgramStage " + event.getProgramStage() + " is not repeatable. Current payload contains duplicate event" )
We can do it here probably much better than `ProgramStageCheck` 

Does `WorkContext` contain the entire event list from the payload?

2020-09-28 12:29 UTC, luciano-fiandesio commented on dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
> +                "ProgramStage " + event.getProgramStage() + " is not repeatable. Current payload contains duplicate event" )
No, each validation check checks only one event at the time. The events are not stored in the `WorkContext`

2020-09-28 17:03 UTC, luciano-fiandesio commented on dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
> +    private boolean isValidEvent(final WorkContext workContext, Event event, Set<String> importableStageEvents, final ImportSummaries importSummaries )
`EventManager` does not execute any validation, it delegates to the validation framework.

2020-09-29 16:55 UTC, abyot commented
> Please see comments. In general, I think the logic that is used in the PR is very similar to what we already have in `ProgramInstanceRepeatableStageCheck`.
> Additionally, I'm not sure I understand the concept of "duplicated" event: it seems to me that the duplication is based on `String eventContextId = programStage.getUid() + "-" + event.getEnrollment();`. Is that correct?

Yes, similar but different. What we need to check here is duplicate within the current payload. The only way to detect duplicate here is to map events of a given enrollment and program stage combination. We say there is a duplicate - **only in the context of program with registration** - if the payload contains multiple events for a program stage which is not configured as repeatable.

2020-09-29 16:56 UTC, abyot commented on dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
> +            final ImportSummary is = new ImportSummary( ERROR, "Program " + event.getProgram() + " does not point to a valid program" )
check for program is now left for `ProgramCheck`

2020-09-30 08:21 UTC, luciano-fiandesio approved these changes
Looks great Abyot, thanks for addressing my comments.

2020-10-02 07:21 UTC, stian-sandvold approved these changes

2020-10-02 07:21 UTC, merged