Enabling context variable to define dhis2_home
dhis2/dhis2-core pull request #6424
Opened 2020-10-17 22:22 UTC by delcroip

To be able to set the dhis2 home from a context var instead of system property so one can have multiple DHIS2 running without messing the env variable (and running multiple tomcat)

Solution inspired from https://stackoverflow.com/questions/372686/how-can-i-specify-system-properties-in-tomcat-configuration-on-startup

not tested

2020-10-17 22:30 UTC, delcroip commented
I need to test it before doing the PR

2020-10-19 07:10 UTC, stian-sandvold requested changes
Hey! Thanks for the contribution @delcroip !

There were some code style issues I pointed out, but overall this looks good :) I changed the PR title to reflect our semantic naming conventions for PRs as well (See the check that failed).

2020-10-19 07:10 UTC, stian-sandvold commented on dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/location/DefaultLocationManager.java
> +
Remove empty lines

2020-10-19 07:10 UTC, stian-sandvold commented on dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/location/DefaultLocationManager.java
> +        else{
brackets goes on new lines:
```
if()
{
}
else
{
}
```

2020-10-19 07:10 UTC, stian-sandvold commented on dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/location/DefaultLocationManager.java
> +                Context envCtx = (Context) initCtx.lookup("java:comp/env");
space between method parameters and paranthesis

`lookup( "java..." );`

2020-10-19 07:10 UTC, stian-sandvold commented on dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/location/DefaultLocationManager.java
> +                path = (String)envCtx.lookup(this.contextVariable);
space in paranthesis

2020-10-19 07:10 UTC, stian-sandvold commented on dhis-2/dhis-support/dhis-support-external/src/main/java/org/hisp/dhis/external/location/DefaultLocationManager.java
> +            }catch (NamingException e) {
space in paranthesis + new line for brackets

2020-10-29 15:01 UTC, delcroip commented
Hello 

I am wondering if I should do the PR on the master instead of 2.34, could you tell me ?

br

2020-11-04 10:13 UTC, larshelge commented
@delcroip Yes please raise this PR against master and not 2.34. We always accept PR against master first, and we can then consider backporting it.

2020-11-05 07:37 UTC, delcroip commented
Replace by PR https://github.com/dhis2/dhis2-core/pull/6573

2020-11-05 07:37 UTC, closed without merging