fix: support serialize embeddedObject for audit
dhis2/dhis2-core pull request #6579
Opened 2020-11-05 19:10 UTC by vietnguyen

Add code to handle EmbeddedObject using same logic. That is if the embeddedObject contains IdentifiableObject, only uid of those objects will be serialized.

2020-11-06 09:52 UTC, netroms requested changes

2020-11-06 09:52 UTC, netroms commented on dhis-2/dhis-support/dhis-support-artemis/src/main/java/org/hisp/dhis/artemis/audit/listener/AbstractHibernateListener.java
> +
Double newline

2020-11-06 09:56 UTC, netroms commented
There is some use of import static com.cronutils.utils.Preconditions.checkNotNull;
This should be either java.util.Objects.requireNonNull or com.google.common.base.Preconditions.checkNotNull;

2020-11-09 11:30 UTC, stian-sandvold approved these changes

2020-11-09 21:38 UTC, vietnguyen commented
> There is some use of import static com.cronutils.utils.Preconditions.checkNotNull;
> This should be either java.util.Objects.requireNonNull or com.google.common.base.Preconditions.checkNotNull;

Fixed those

2020-11-10 08:16 UTC, netroms approved these changes

2020-11-10 08:17 UTC, merged