fix: api test error
dhis2/dhis2-core pull request #6614
Opened 2020-11-10 09:51 UTC by vietnguyen

2020-11-10 10:34 UTC, netroms approved these changes

2020-11-10 10:37 UTC, vilkg requested changes
It didn't fix the tests :(

2020-11-11 06:34 UTC, netroms approved these changes

2020-11-11 08:40 UTC, vilkg approved these changes

2020-11-11 08:53 UTC, merged