fix: NPE when retrieving relationship with event
dhis2/dhis2-core pull request #6699
Opened 2020-11-17 10:47 UTC by stian-sandvold

2020-11-17 13:56 UTC, enricocolasante approved these changes

2020-11-19 06:22 UTC, netroms approved these changes

2020-11-19 07:58 UTC, luciano-fiandesio requested changes

2020-11-19 07:58 UTC, luciano-fiandesio commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/TrackerBundleParamsConverter.java
> +            .peek( enrollment -> updateEnrollmentReferences( enrollment, enrollment.getTrackedEntity() ) )
As we discussed, make sure that we only generate UID for `enrollment.getEnrollment()`
The `trackedEntity` property should be left empty if it's not present in the original payload

```
Enrollment:
updateReference(enrollment.getEnrollment)
enrollment.getTei -> isEmpty() ? null : tei
```

2020-11-19 07:58 UTC, luciano-fiandesio commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/TrackerBundleParamsConverter.java
> +            enrollment.setNotes( enrollment.getNotes().stream()
As we discussed, make sure that we only generate UID for `event.setEvent()`
The `trackedEntity` and `enrollment` property should be left empty if it's not present in the original payload.

```
Event:
UpdateReference(event.getEvent)
event.getEnrollment -> isEmpty() ? null : enrollment
event.getTei -> isEmpty()? null : tei
```

2020-12-17 08:29 UTC, merged