fix: DHIS2-9894 user assignment is checked through ProgramStage definition
dhis2/dhis2-core pull request #6720
Opened 2020-11-19 15:11 UTC by gnespolino

2020-11-19 19:34 UTC, stian-sandvold approved these changes

2020-11-20 08:05 UTC, enricocolasante requested changes
Small changes

2020-11-20 08:05 UTC, enricocolasante commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/AssignedUserValidationHook.java
> +            TrackerIdScheme.UID, ProgramStage.class, event.getProgramStage() )).isEnableUserAssignment();
```suggestion
        Boolean userAssignmentEnabled = ctx.getProgramStage( event.getProgramStage() ).isEnableUserAssignment();
```

2020-11-20 08:05 UTC, enricocolasante commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/AssignedUserValidationHook.java
> +                    .addArg( event.getAssignedUser() );
```suggestion
                addError( reporter, E1118, event.getAssignedUser() );
```

2020-11-20 12:50 UTC, enricocolasante approved these changes

2020-11-23 08:23 UTC, stian-sandvold approved these changes

2020-11-23 08:23 UTC, merged