fix: Add unique constraint to program rule name property [DHIS2-9972]
dhis2/dhis2-core pull request #6929
Opened 2020-12-17 08:30 UTC by zubaira

2020-12-17 14:30 UTC, enricocolasante requested changes
Is it a requirement that the program rule name is unique across programs?

We should check that and if so we need to be sure in the flyway script that we do not have duplicates in the name column

2020-12-18 06:18 UTC, zubaira commented
> Is it a requirement that the program rule name is unique across programs?
> 
> We should check that and if so we need to be sure in the flyway script that we do not have duplicates in the name column

yes for that we have flyway script 
https://github.com/dhis2/dhis2-core/blob/master/dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v36/V2_36_2__normalize_program_rule_names_for_duplicates.java

2020-12-18 07:13 UTC, enricocolasante approved these changes

2020-12-18 09:03 UTC, ameenhere approved these changes

2020-12-18 13:42 UTC, merged