feat: change user property name to createdBy
dhis2/dhis2-core pull request #7061
Opened 2021-01-08 09:05 UTC by vietnguyen

2021-01-14 04:09 UTC, mortenoh approved these changes

2021-01-14 12:45 UTC, stian-sandvold approved these changes

2021-01-14 12:47 UTC, stian-sandvold commented
Good work @vietnguyen . I see a few automatic comments from github in the files, did you have a look at them? Some seem sensible to check out.

There is also 1 "critical" issue from SonarCloud check, related to using a constant for "createdBy" in one of the files, would be great to add that to please sonarCloud :)

2021-01-19 09:16 UTC, larshelge commented
Let's make the `createdBy` property unmodifiable / immutable.

2021-01-19 09:24 UTC, larshelge requested changes
Let's make the `createdBy` field immutable / not modifiable.

2021-01-19 09:25 UTC, larshelge commented
Remember to upgrade the change note and share with front-end team.

2021-01-26 09:11 UTC, larshelge commented on dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/BaseIdentifiableObject_.java
> +                                     * Copyright (c) 2004-2021, University of Oslo
Remove license.

2021-01-26 12:37 UTC, vietnguyen commented on dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/BaseIdentifiableObject_.java
> +                                     * Copyright (c) 2004-2021, University of Oslo
fixed

2021-01-26 14:24 UTC, vietnguyen commented
> Let's make the `createdBy` field immutable / not modifiable.
@larshelge 
- Removed the HibernateListener solution as it may cause performance issue.
- Added code to ignore `createdBy` field in `IdentifiableObjectBundleHook.preUpdate`
- Test covered by `MetadataImportServiceTest#testUpdateImmutableCreatedByField`

2021-02-02 11:34 UTC, merged