DHIS2-8911 Making sql script idempotent
dhis2/dhis2-core pull request #7191
Opened 2021-01-26 13:32 UTC by gnespolino

2021-01-26 13:54 UTC, ameenhere approved these changes

2021-01-26 14:02 UTC, ameenhere requested changes
Not sure if a pr to patch/2.35.1 is required. Since 2.35.1 is already released.

2021-01-27 08:12 UTC, stian-sandvold approved these changes

2021-01-27 08:13 UTC, stian-sandvold commented
Yes, that is right @ameenhere . Now it would be a merge to 2.35, then next mino version it will be included

2021-01-28 08:30 UTC, closed without merging

2021-01-28 08:30 UTC, gnespolino commented
Closing this then