feat: add Translatable annotation
dhis2/dhis2-core pull request #7267
Opened 2021-02-04 07:41 UTC by vietnguyen

2021-02-04 08:13 UTC, netroms commented
Mini typo: 
> response will have **to** > Two? attributes related to translation :

2021-02-04 08:49 UTC, netroms approved these changes

2021-02-04 13:08 UTC, larshelge commented on dhis-2/dhis-services/dhis-service-schema/src/test/java/org/hisp/dhis/schema/TranslatablePropertyIntrospectorTest.java
> +                             * Copyright (c) 2004-2020, University of Oslo
Remove license.

2021-02-04 13:25 UTC, mortenoh commented
Please merge with master and apply formatting

2021-02-06 13:16 UTC, vietnguyen commented
> Please merge with master and apply formatting

Done

2021-02-06 13:16 UTC, vietnguyen commented on dhis-2/dhis-services/dhis-service-schema/src/test/java/org/hisp/dhis/schema/TranslatablePropertyIntrospectorTest.java
> +                             * Copyright (c) 2004-2020, University of Oslo
fixed

2021-02-09 07:47 UTC, larshelge commented
I was wondering if we could just infer the translation key from the get-method based on naming convention. The naming convention is:

`getDisplay{PropertyName}`

E.g. if the get-method is called `getDisplayShortName()`, we can infer the property to be `shortName`.

It would also be interesting to re-use the @ Property annotation with a `translateable = true` argument, instead of having a new annotation. Not sure if that is possible/feasible.

2021-02-17 08:21 UTC, netroms approved these changes

2021-02-18 07:17 UTC, mortenoh requested changes

2021-02-18 07:17 UTC, mortenoh commented on dhis-2/dhis-api/src/main/java/org/hisp/dhis/validation/ValidationRule.java
> +    @Translatable( propertyName = "instruction", key = "NSTRUCTION" )
Should be `INSTRUCTION` ?

2021-02-18 08:15 UTC, vietnguyen commented on dhis-2/dhis-api/src/main/java/org/hisp/dhis/validation/ValidationRule.java
> +    @Translatable( propertyName = "instruction", key = "NSTRUCTION" )
fixed

2021-02-18 09:13 UTC, mortenoh approved these changes

2021-02-18 09:13 UTC, merged