fix: DHIS2-10674: Fixing 'access' for charts and reportTables
dhis2/dhis2-core pull request #7604
Opened 2021-03-11 14:21 UTC by maikelarabori

As we have to still support Chart and ReportTable, but behind the scenes, all rules and tables are tight to Visualization, we need to add a "special condition" in order to load the "access" for the Visualization associated with the legacy object returned (Chart or Visualization).
Otherwise, we end up with a different/invalid "access" for Chart and ReportTable.

This PR will ensure the "access" is consistent across all those three entities.
This code must be removed once we completely drop the support for Chart and ReportTable.

2021-03-15 09:30 UTC, mortenoh requested changes

2021-03-15 09:30 UTC, mortenoh commented on dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/ConversionHelper.java
> +        if ( isNotEmpty( entities ) )
Maybe better with !isNotEmpty(..) then return?

2021-03-15 09:30 UTC, mortenoh commented on dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/ConversionHelper.java
> +        if ( chart != null )
Maybe better with if chart == null then return? too many levels on indentation is not good

2021-03-15 09:30 UTC, mortenoh commented on dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/ConversionHelper.java
> +        if ( isNotEmpty( entities ) )
!isNotEmpty(...)

2021-03-15 09:30 UTC, mortenoh commented on dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/ConversionHelper.java
> +        if ( reportTable != null )
Same above

2021-03-15 13:36 UTC, larshelge commented
Just a note, we have decided to remove the `Chart` and `ReportTable` APIs, as well as the classic pivot table app in 2.37. This might still be helpful in case we plan to backport this fix.

2021-03-18 09:14 UTC, larshelge approved these changes

2021-03-18 09:15 UTC, merged