fix: [DHIS2-10702] - Unexpected error querying tracked entity instance
dhis2/dhis2-core pull request #7722
Opened 2021-03-22 16:52 UTC by lucaCambi77

If we create a tracked entity type as metadata import that contains a reference to tracked entity attributes, we are not checking if those attributes actually exist.
This fix adds tracked entity type validation and sql clean up scripts

- [x] adds tracked entity type validation hook where tracked entity atrrtibute reference is checked 
- [ ] adds sql clean up script and foreign key

2021-03-23 13:13 UTC, ameenhere requested changes

2021-03-23 13:13 UTC, ameenhere commented on dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.33/V2_33_38__Add_not_null_trackedentitytypeattribute_foreign_keys.sql
> +ALTER TABLE trackedentitytypeattribute ALTER COLUMN trackedentityattributeid SET NOT NULL;
You can club both the scripts into one file instead of having them as separate scripts.

2021-03-23 15:13 UTC, ameenhere approved these changes

2021-03-24 12:44 UTC, gnespolino approved these changes
Good job, it looks correct, however, we should respect coding conventions also in 2.33 branch, even if formatting plugin is not setup for this version

2021-03-24 14:59 UTC, merged