fix: [DHIS2-10702] - Unexpected error querying tracked entity instance 2.34
dhis2/dhis2-core pull request #7734
Opened 2021-03-24 10:58 UTC by lucaCambi77

see https://github.com/dhis2/dhis2-core/pull/7722

2021-03-24 12:47 UTC, gnespolino approved these changes

2021-03-24 12:47 UTC, gnespolino commented on dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackedentity/TrackedEntityType.java
> + * Copyright (c) 2004-2019, University of Oslo
should be 2021

2021-03-24 12:47 UTC, gnespolino commented on dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/TrackedEntityTypeObjectBundleHookTest.java
> + * Copyright (c) 2004-2019, University of Oslo
should be 2021

2021-03-24 12:47 UTC, gnespolino commented on dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/TrackedEntityTypeValidationTest.java
> + * Copyright (c) 2004-2020, University of Oslo
same here

2021-03-29 08:56 UTC, stian-sandvold commented on dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.33/V2_33_36__Add_translations_column_into_programruleaction_table.sql
> +alter table programruleaction add column if not exists translations jsonb;
This is a script for 2.33, and not 2.34, so it should be fixed on the 2.33 branch, not 2.34. Or is this a relevant problem for 2.34?

I would in either case suggest removing this file from this PR, and fixing it in a separate PR

2021-03-29 08:56 UTC, stian-sandvold requested changes
See comment about flyway script for 2.33

2021-03-29 09:47 UTC, stian-sandvold approved these changes

2021-03-29 09:47 UTC, merged