fix: [DHIS2-10702] - Unexpected error querying tracked entity instance porting 2.35
dhis2/dhis2-core pull request #7735
Opened 2021-03-24 11:12 UTC by lucaCambi77

see https://github.com/dhis2/dhis2-core/pull/7722

2021-03-24 12:48 UTC, gnespolino approved these changes
Please check license, it should be 2021 everywhere as mentioned in the other PR

2021-03-29 08:55 UTC, stian-sandvold commented on dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.33/V2_33_36__Add_translations_column_into_programruleaction_table.sql
> +alter table programruleaction add column if not exists translations jsonb;
This is a script for 2.33, and not 2.35, so it should be fixed on the 2.33 branch, not 2.35. Or is this a relevant problem for 2.35?

I would in either case suggest removing this file from this PR, and fixing it in a separate PR

2021-03-29 08:55 UTC, stian-sandvold requested changes
See comment about flyway script for 2.33

2021-03-29 09:46 UTC, stian-sandvold approved these changes

2021-03-29 09:50 UTC, merged