fix: [DHIS2-10702] - Unexpected error querying tracked entity instance porting 2.37
dhis2/dhis2-core pull request #7741
Opened 2021-03-24 12:35 UTC by lucaCambi77

see https://github.com/dhis2/dhis2-core/pull/7722

2021-03-24 12:48 UTC, gnespolino approved these changes
Please check license, it should be 2021 everywhere as mentioned in the other PR

2021-03-29 07:44 UTC, enricocolasante requested changes
Check the flyway scripts

2021-03-29 07:44 UTC, enricocolasante commented on dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.33/V2_33_36__Add_translations_column_into_programruleaction_table.sql
> +alter table programruleaction add column if not exists translations jsonb;
This script should be here?
New out of order scripts will break the build

2021-03-29 10:50 UTC, enricocolasante approved these changes

2021-03-29 14:11 UTC, merged