feat: Add description test for extractDataMatrixValue function [DHIS2-12364]
dhis2/dhis2-core pull request #9795
Opened 2022-02-11 20:42 UTC by zubaira

2022-02-16 08:26 UTC, enricocolasante requested changes
Shouldn't you bump rule-engine version in the pom?

2022-02-16 08:28 UTC, zubaira commented
> Shouldn't you bump rule-engine version in the pom?

done

2022-02-17 10:53 UTC, gnespolino approved these changes

2022-02-18 08:04 UTC, enricocolasante approved these changes

2022-02-18 08:58 UTC, merged