fix: Fix NPE checking for null org unit [DHIS2-12713]
dhis2/dhis2-core pull request #9957
Opened 2022-03-03 12:10 UTC by enricocolasante

2022-03-03 15:02 UTC, lucaCambi77 approved these changes

2022-03-04 05:36 UTC, teleivo requested changes

2022-03-04 05:36 UTC, teleivo commented on dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/DefaultTrackerAccessManager.java
> +                if ( !canAccess( user, program, ou ) )
I think you can merge these if statements into one. Maybe even better, make canAccess null safe.

2022-03-04 07:59 UTC, teleivo approved these changes

2022-03-04 08:04 UTC, merged