fix: Skip fileResource.issAssigned check for CREATE
dhis2/dhis2-core pull request #9979
Opened 2022-03-04 10:14 UTC by abyot

2022-03-04 11:34 UTC, stian-sandvold approved these changes

2022-03-09 13:05 UTC, enricocolasante requested changes
You can consider using the strategy to check if it is a create, it makes the code more explicit.

Anyway, you need to merge master into your branch as the ValidationContext was removed in a previous PR. I am really not sure why github is not showing this as a problem

2022-03-09 13:05 UTC, enricocolasante commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidationHook.java
> +        if ( reporter.getValidationContext().getProgramStageInstance( event.getEvent() ) == null )
```suggestion
        if ( reporter.getBundle().getStrategy(event).isCreate() ) {
```

2022-03-09 13:05 UTC, enricocolasante commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/TrackedEntityAttributeValidationHook.java
> +        if ( reporter.getValidationContext().getTrackedEntityInstance( te.getTrackedEntity() ) == null )
```suggestion
        if ( reporter.getBundle().getStrategy( te ).isCreate() ) {
```

2022-03-11 08:12 UTC, abyot commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventDataValuesValidationHook.java
> +        if ( reporter.getValidationContext().getProgramStageInstance( event.getEvent() ) == null )
fixed.

2022-03-11 08:12 UTC, abyot commented on dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/TrackedEntityAttributeValidationHook.java
> +        if ( reporter.getValidationContext().getTrackedEntityInstance( te.getTrackedEntity() ) == null )
fixed.

2022-03-11 08:17 UTC, enricocolasante approved these changes

2022-03-11 08:29 UTC, merged